Repository Speechpeach/speech-backend, pull requests merged in 2024-04, with the labels that each got.

#4 [TASK-355] PR 템플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#6 [TASK-354] Github Actions로 CI 테스트(동적) 체인 구축
  .github/workflows/ci-test.yaml
  build.gradle
Labels: ⚙️ Setting, ✅ Test

#5 [TASK-353] swagger 환경설정
  build.gradle
  src/main/java/com/speechpeach/speech/global/swagger/SwaggerConfig.java
  src/main/java/com/speechpeach/speech/global/swagger/SwaggerTestController.java
  src/main/java/com/speechpeach/speech/global/swagger/SwaggerUser.java
  src/main/resources/application.yml
Labels: ⚙️ Setting

#9 [TASK-395] 로그인 기능 구현 전, 임시용 User 저장 및 조회 기능 구현
  build.gradle
  src/main/java/com/speechpeach/speech/global/exception/ExceptionCode.java
  src/main/java/com/speechpeach/speech/user/entity/User.java
  src/main/java/com/speechpeach/speech/user/repository/UserRepository.java
  src/main/java/com/speechpeach/speech/user/service/UserService.java
  src/test/java/com/speechpeach/speech/SpeechApplicationTests.java
  src/test/java/com/speechpeach/speech/user/repository/UserRepositoryTest.java
Labels: ✨ Feature

#10 [TASK-397] BaseEntity 생성
  build.gradle
  src/main/java/com/speechpeach/speech/global/config/AuditConfig.java
  src/main/java/com/speechpeach/speech/global/entity/BaseEntity.java
  src/test/java/com/speechpeach/speech/global/entity/BaseEntityTest.java
Labels: ⚙️ Setting

#13 [TASK-407] 영상관련 도메인 Entity 생성
  src/main/java/com/speechpeach/speech/record/entity/Record.java
  src/main/java/com/speechpeach/speech/videoScript/entity/VideoScript.java
  src/main/java/com/speechpeach/speech/youtubeVideo/entity/YoutubeVideo.java
  src/main/java/com/speechpeach/speech/youtubeVideo/entity/YoutubeVideoLike.java
Labels: ✨ Feature
